### ISSUE TITLE
Delete collection before import ?

### ISSUE THREAD

**Issue by boly38** [Azure/azure-documentdb-datamigrationtool#11]
(maybe not ideal to put a question here, but I was unable to find "dt.exe" discussion forum and maybe this should be undertaken as improvement...)

I have written a powershell script that use "dt.exe" tool to backup/restore docdb to/from blobstorage JSON file. It's a very usefull tool and thanks for that!

Now I would like a way to clean a given docdb collection before importing data.
(My understanding) today seems like there is no way to do that. You could of course update existing entry following unique id (using "/t.IdField:id", "/t.UpdateExisting"), but you couldn't enforce to delete deprecated entry (that doesn't match the backup JSON file). Am I right to say that ?

So does exist a "dt.exe" option to delete docdb destination collection(s) before importing data ?
if no, then is this feature planned ? or maybe does exist a simple powershell way to do that ?

thanks

NB: question also posted here : https://azure.microsoft.com/en-us/documentation/articles/documentdb-import-data/

**Comment by nahk-ivanov** [comment]
That is correct, there is no option to delete a collection and we didn't plan for the feature, but you should be able to use standard .NET DocumentDB SDK from PowerShell to delete a collection.
Here's a quick sample (it requires some error handling, but you can pick up the idea):

```
Add-Type -Path 'Newtonsoft.Json.dll'
Add-Type -Path 'Microsoft.Azure.Documents.Client.dll'

# Create DocumentDB client
$client = New-Object Microsoft.Azure.Documents.Client.DocumentClient `
    -Args ([Uri]'https://<account-name>.documents.azure.com:443/'), '<account-key>'

# Find the database by name
$database = 
    $client.ReadDatabaseFeedAsync($null).Result `
    | where { $_.Id -eq '<database-name>' }`
    | select -First 1

# Find the collection by name
$collection =
    $client.ReadDocumentCollectionFeedAsync($database.SelfLink, $null).Result `
    | where { $_.Id -eq '<collection-name>' }`
    | select -First 1

# Delete the collection
$client.DeleteDocumentCollectionAsync($collection.SelfLink, $null).Wait()
```

Both [JSON.NET](https://www.nuget.org/packages/Newtonsoft.Json/6.0.8) and [DocumentDB SDK](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/) are available through the NuGet.

I will close the issue for now, as it can be easily achieved from external.
