### ISSUE TITLE
Reset data via Powershell

### ISSUE THREAD

**Issue by ThomasVandenbon** [Azure/azure-documentdb-datamigrationtool#111]
Is there a way to reset databases and containers using Powershell?
Similar as to how this is possible via "Reset data...".

I've noticed that I can use the Cosmos Data Migration Tool to automatically create the necessary Databases and Containers (which is great), but I can't find a way to delete these Databases and Containers when I want to reset the data.

**Comment by nahk-ivanov** [comment]
Hi,

You can delete databases or containers through PowerShell. Documentation is available [here](https://docs.microsoft.com/en-us/azure/cosmos-db/manage-with-powershell#azure-cosmos-database).

Regards,
Alex.
