### ISSUE TITLE
DocumentDB account end-point URL should be provided as part of the connection string

### ISSUE THREAD

**Issue by pooran** [Azure/azure-documentdb-datamigrationtool#117]
What is the correct format for adding end-point url for connection string? I am getting the error in subject

**Comment by pooran** [comment]
I am using MongoDB setting

**Comment by pavlovmilen** [comment]
I have similar issue with the target information section, the format for the Source connection string is:
`mongodb://<dbuser>:<dbpassword>@<host>:<port>/<databaseName>/?ssl=true&replicaSet=globaldb`
It is valid for **Source information** but not for **Target Information**.

**Comment by pavlovmilen** [comment]
According to the [documentation ](https://docs.microsoft.com/en-us/azure/cosmos-db/import-data#MongoDB) the format for **Target** is different
`AccountEndpoint=<https://mydbname.documents.azure.com:443/>;AccountKey=<CosmosDB Key>;Database=<CosmosDB Database>;`

**Comment by CSolervicens** [comment]
Where can I find the key, in the docs i found a link about, but in the document there was nothing about...
AccountKey=<CosmosDB Key>

**Comment by mweel1** [comment]
+1
