### ISSUE TITLE
Add MongoDB 3.x support

### ISSUE THREAD

**Issue by CraigKennedy** [Azure/azure-documentdb-datamigrationtool#13]
It looks like this app is using the legacy mongo nuget package.  I'm having trouble connecting to a mongo 3.0.9 database with the provided connection string box.  Any chance on this getting upgraded to the newer driver and supporting 3.x and above?

**Comment by CraigKennedy** [comment]
Any news on when 3.x support would show up?  I'm not able to connect to my instance of 3.x with SCRAM + SSL.

**Comment by nahk-ivanov** [comment]
Hello,

Sorry for the delay. We are considering this for our next release, but don't have any timeline yet.

Meanwhile, considering they didn't change `mongoexport` format, you should be able to export your data from Mongo and import to Document DB using our custom `MongoDBExport` source (`MongoDB export (mongoexport) JSON file(s)` in the UI version of the tool).

Thanks,
Alex.

**Comment by nahk-ivanov** [comment]
Resolved in 12dee7c3f05cb0b5e4bf540dba4645ba87f265ad.
