### ISSUE TITLE
TLS version mismatch

### ISSUE THREAD

**Issue by kunjald13** [Azure/azure-documentdb-datamigrationtool#131]
Currently Azure portal's storage account has TLS 1.2 as the minimum supported TLS version.
However the DMT tool is still using TLS 1.0 causing errors when the source is JSON files from BLOB storage.

The tool fails with an unhandled exception message "The remote server returned an error: (400) Bad Request"

Instead of forcing users of the tool to lower the TLS protocol in Azure portal, kindly provide an option on the tool to select the protocol.

The technical details from the unhandled exception is attached below
[DMT Error.txt](https://github.com/Azure/azure-documentdb-datamigrationtool/files/6164626/DMT.Error.txt)

**Comment by viswa-optimusprime** [comment]
@All - is the issue fixed in any of the version ? Is it possible to expedite this request ? Can someone help ? or is there workaround?

**Comment by kunjald13** [comment]
@viswa-optimusprime  - There is a workaround. Download the zip version of the tool and open dtui.exe.config and add the following configuration under <configuration><runtime>
<AppContextSwitchOverrides value="Switch.System.Net.DontEnableSystemDefaultTlsVersions=false"/>
NOTE: <configuration><runtime> will already have other entries for <assemblybinding>

A value of false for Switch.System.Net.DontEnableSystemDefaultTlsVersions causes app to adopt the TLS version of the host operating system. By default Windows 10 build 1507 and upwards support TLS 1.2.

Hope that helps!!!
Regards
KD

**Comment by viswa-optimusprime** [comment]
@kunjald13 -  am not seeing the configuration. This is the config file content. Its looking for Section name and types..


<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="dataTransfer.sources" type="Autofac.Configuration.ComponentsConfigurationSection, Microsoft.DataTransfer.Autofac" />
    <section name="dataTransfer.sinks" type="Autofac.Configuration.ComponentsConfigurationSection, Microsoft.DataTransfer.Autofac" />
    <section name="dataTransfer.configurationFactories" type="Autofac.Configuration.ComponentsConfigurationSection, Microsoft.DataTransfer.Autofac" />
  </configSections>
  <dataTransfer.sources>
    <add name="DocumentDB" type="Microsoft.DataTransfer.DocumentDb.Source.DocumentDbSourceAdapterFactory, Microsoft.DataTransfer.DocumentDb" />
    <add name="HBase" type="Microsoft.DataTransfer.HBase.Source.HBaseSourceAdapterFactory, Microsoft.DataTransfer.HBase" />
    <add name="DynamoDB" type="Microsoft.DataTransfer.DynamoDb.Source.DynamoDbSourceAdapterFactory, Microsoft.DataTransfer.DynamoDb" />
    <add name="AzureTable" type="Microsoft.DataTransfer.AzureTable.Source.AzureTableSourceAdapterFactory, Microsoft.DataTransfer.AzureTable" />
    <add name="CsvFile" type="Microsoft.DataTransfer.CsvFile.Source.CsvFileSourceAdapterFactory, Microsoft.DataTransfer.CsvFile" />
    <add name="SQL" type="Microsoft.DataTransfer.Sql.Source.SqlDataSourceAdapterFactory, Microsoft.DataTransfer.Sql" />
    <add name="MongoDBExport" type="Microsoft.DataTransfer.MongoDb.Source.Mongoexport.MongoexportFileSourceAdapterFactory, Microsoft.DataTransfer.MongoDb" />
    <add name="MongoDB" type="Microsoft.DataTransfer.MongoDb.Source.Online.MongoDbSourceAdapterFactory, Microsoft.DataTransfer.MongoDb" />
    <add name="JsonFile" type="Microsoft.DataTransfer.JsonFile.Source.JsonFileSourceAdapterFactory, Microsoft.DataTransfer.JsonFile" />
  </dataTransfer.sources>
  <dataTransfer.sinks>
    <add name="JsonFile" type="Microsoft.DataTransfer.JsonFile.Sink.JsonFileSinkAdapterFactory, Microsoft.DataTransfer.JsonFile" />
    <add name="DocumentDB" type="Microsoft.DataTransfer.DocumentDb.Sink.Parallel.DocumentDbParallelSinkAdapterFactory, Microsoft.DataTransfer.DocumentDb" />
    <add name="DocumentDBBulk" type="Microsoft.DataTransfer.DocumentDb.Sink.Bulk.DocumentDbBulkSinkAdapterFactory, Microsoft.DataTransfer.DocumentDb" />
    <add name="TableAPIBulk" type="Microsoft.DataTransfer.TableAPI.Sink.Bulk.TableAPIBulkSinkAdapterFactory, Microsoft.DataTransfer.AzureTable" />
  </dataTransfer.sinks>
  <dataTransfer.configurationFactories>
    <add type="Microsoft.DataTransfer.ConsoleHost.DynamicConfiguration.DynamicConfigurationFactory, Microsoft.DataTransfer.ConsoleHost.DynamicConfiguration" />
  </dataTransfer.configurationFactories>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Autofac" publicKeyToken="17863af14b0044da" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.0.0" newVersion="3.5.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.SqlServer.Types" publicKeyToken="89845dcd8080cc91" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Services.Client" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.8.3.0" newVersion="5.8.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.OData" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.8.3.0" newVersion="5.8.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Edm" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.8.3.0" newVersion="5.8.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Azure.Documents.Client" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.OData.Core" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-7.5.1.20914" newVersion="7.5.1.20914" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

**Comment by kunjald13** [comment]
The xml styled tags that i had included in my response are not being displayed. 
Open dtui.exe.config and find section
`<configuration><runtime>` and add the following line 
`<AppContextSwitchOverrides value="Switch.System.Net.DontEnableSystemDefaultTlsVersions=false"/>`

After the edit that section should look like given below.
`  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
  </startup>
  <runtime>
  <AppContextSwitchOverrides value="Switch.System.Net.DontEnableSystemDefaultTlsVersions=false"/>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Autofac" publicKeyToken="17863af14b0044da" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.0.0" newVersion="3.5.0.0" />
      </dependentAssembly>
`
See the next response where i have attached a screenshot as well. You have to add line number 44.

**Comment by kunjald13** [comment]
![dtui_exe_config](https://user-images.githubusercontent.com/79849006/121252718-f6d1f700-c8c5-11eb-85ad-55af4bee0f8a.jpg)
