### ISSUE TITLE
Still Supported?

### ISSUE THREAD

**Issue by brianandreasen1983** [Azure/azure-documentdb-datamigrationtool#133]
Hello Microsoft or anyone who is maintaining this product.

Our organization recently tried to use the last known good build of the Azure Cosmos DB Migration Tool and we had encountered many issues and errors.

We downloaded the source file and changes the .NET Framework runtime version to get past the bad request (400) error due to a incompatibility between .NET Framework and TLS 1.2 in Cosmos to verify our connection string. That being said we still encountered issues when setting the target to migrate our data to.

Our use case is migrating data from Azure Table Storage to Azure Cosmos DB, however, our cosmos DB Instance is using Table API which means we can't use Azure Data Factory because there are no connectors for it.

When setting the connection string for our destination we encountered an error such as DocumentDBConnectionString......I'll try to reproduce and repost it here but it wasn't allowing us to verify our connection string of our Cosmos DB instance.

Will this tool ever be fixed or will enterprises need to write their own tools here on out?

The docs for this tool specify nothing about how to fix the TLS 1.2 incompatibility error for this tool nor that it is an issue or anything else. While this tool exists in the azure documentation I'm questioning whether this tool is still supported since it has been over 3 years since the last release.

Is this still supported?

In the end we wrote our own tool.

**Comment by rbev** [comment]
I am also having this issue - i might downlaod hte source and have a go at updating the framework

**Comment by rbev** [comment]
Looks like there is a PR #124 up to fix this
