### ISSUE TITLE
It is not working at all.

### ISSUE THREAD

**Issue by untecnologo** [Azure/azure-documentdb-datamigrationtool#139]
Hello guys, I have been trying to do something simple as getting a local JSON backup from a cosmos DB collection, and all the processes run in 1.6 seconds, not output error and a  JSON file completely empty. I used to use version 1.3 I think so, but this version does not connect anymore. Now, the new version connects but it does not work for me.

**Comment by isaacbromberg** [comment]
The same results, but I found why: I had a typo in the collection name. As a result, no error, but zero transferred and zero errors.
