### ISSUE TITLE
Can not find dt.exe

### ISSUE THREAD

**Issue by AroraMunish** [Azure/azure-documentdb-datamigrationtool#167]
The document https://docs.microsoft.com/en-us/azure/cosmos-db/table/table-import mentions to download data migration tool from this github location. Here-in I can not find dt.exe

<img width="726" alt="Data Migration Tool" src="https://user-images.githubusercontent.com/13214220/152120185-deb92220-faad-4018-806f-8a93b125b806.png">

**Comment by shubhampan97** [comment]
Here's a link from Microsoft download center:
[https://www.microsoft.com/en-us/download/details.aspx?id=46436](url)

**Comment by chshihMSFT** [comment]
![image](https://user-images.githubusercontent.com/45855145/160522903-746d4a2b-3c45-43b6-8615-4e0c4ef8afd0.png)

Please check pre-compiled in Releases section.
https://github.com/Azure/azure-documentdb-datamigrationtool/releases/tag/1.8.3
In case you bump into any Table migration issue, please git clone this repo and build entire solution via Visual Studio, this should restore correct versions of NuGet packages.

The console command tool - **dt.exe** could be found in _\azure-documentdb-datamigrationtool\Console\Microsoft.DataTransfer.ConsoleHost\bin\Debug_

GUI tool - **dtui.exe** is in _\azure-documentdb-datamigrationtool\Wpf\Microsoft.DataTransfer.WpfHost\bin\Debug_
