### ISSUE TITLE
Looks like azure portal doesn't support keys anymore

### ISSUE THREAD

**Issue by sgireddy** [Azure/azure-documentdb-datamigrationtool#18]
I am trying to upload local mongodb collections to documentDB on azure. I could not find a way to extract "AccountEndpoint" and "AccountKey". Looks like this tool doesn't support the connection string provided in azure portal.

**Comment by nahk-ivanov** [comment]
Hello sgireddy,

What are you getting in the **Primary Connection String** field when you navigate to **Keys** under your DocumentDB account on Azure portal? It should give you _AccountEndpoint_ and _AccountKey_, but you will have to append a `Database=Xyz` to the provided connection string.

Regards,
Alex.

**Comment by sgireddy** [comment]
I don't see Keys anywhere. All I see is connection strings.

**Comment by sgireddy** [comment]
mongodb://abcdefgh:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxZSHdHyehYfN7btz7p04BOWfvFpdjO1XhGdnlbyg==@abcdefgh.documents.azure.com:10250/rest?ssl=true

I replaced part of the password with xxxx and replaced host name & username with abcdefgh

I tried using abcdefgh as AccountEndpoint and password as Account Key but it didn't work.

**Comment by nahk-ivanov** [comment]
Hi sgireddy,

I think in that case _AccountEndpoint_ will be `https://abcdefgh.documents.azure.com` and password will be _AccountKey_. But since you are using mongo-enabled account, you probably can just use `mongoimport`/`mongorestore` to ingest the data.

Regards,
Alex.

**Comment by sgireddy** [comment]
This helped, thank you. All I missed was "https://" in the account endpoint.

**Comment by AndrewHoh** [comment]
Following up on this, we have instructions on how you can migrate data to your documentdb with protocol support for mongodb database here: https://docs.microsoft.com/azure/documentdb/documentdb-mongodb-migrate
