### ISSUE TITLE
This project's dependencies are messed up.

### ISSUE THREAD

**Issue by edgarhsanchez** [Azure/azure-documentdb-datamigrationtool#19]
I'll look into this a little more but it appears that getting this project from git there seems to be some kind of issue with the build settings or configurations where none of the Nuget Restore options solve the dependency errors.

**Comment by nahk-ivanov** [comment]
Hi!

Are you sure it's not the same as the PR #17 we have?

Regards,
Alex.

**Comment by mcriscolo** [comment]
Just pulled this from GitHub; had to update the public key token in 2 projects - Microsoft.DataTransfer.DocumentDb.FunctionalTests.csproj and Microsoft.DataTransfer.DocumentDb.csproj for the "Microsoft.Azure.Documents.Client.TransientFaultHandling" component.  Builds successfully after updates.

**Comment by nahk-ivanov** [comment]
Fixed in 2aac5c2ccf4ddb9ce3532dfe813394aac189a121.
