### ISSUE TITLE
An error occurred while sending the request

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-documentdb-datamigrationtool#193]
I've tried to use the tool for exporting data from CosmosDb.
I use the valid Connection String with Database=ProxyData at the end.
When I press Verify -

![image](https://user-images.githubusercontent.com/9221694/203156395-5f2500cd-95bc-455b-b04c-d09a67998946.png)

v.1.8.3

**Comment by markjbrown** [comment]
Hello, this repo is no longer active. We are going to archive this repo. Please visit this repo for the current version.
https://github.com/AzureCosmosDB/data-migration-desktop-tool

Thanks.
