### ISSUE TITLE
Sink / Target Naming Convention

### ISSUE THREAD

**Issue by potatoqualitee** [Azure/azure-documentdb-datamigrationtool#197]
Greetings, I'm a 20+ year SQL Server DBA and non-CS person. Maybe my vernacular is out of style and this is the new way but... I had to look up what "sink" meant. Would it be possible to keep or alias the word to the classic "Target" or "Destination" terminology?  Every migration tool I've used uses one of the two terms and I can see having to add an extra slide defining sink when doing presentations on getting SQL Server data to Cosmos.

Thank you 🙏🏼

**Comment by markjbrown** [comment]
Hello, this repo is no longer active. We are going to archive this repo. Please visit this repo for the current version. 
https://github.com/AzureCosmosDB/data-migration-desktop-tool

Thanks.

**Comment by potatoqualitee** [comment]
thanks, looks like i put it i the wrong repo
