### ISSUE TITLE
No Trigger Support

### ISSUE THREAD

**Issue by ijabit** [Azure/azure-documentdb-datamigrationtool#21]
I want to do a simple transformation when documents are created/updated, but this tool doesn't seem to support the use of triggers during upload. Sure you can use the Bulk Insert functionality, but that doesn't work for multi-partitioned collections, which is what I'm using. Please support either the use of BulkTransformationInsert.js to insert into multi-partition collections, or more preferably, support the use of Triggers during import.

**Comment by ijabit** [comment]
Bump

**Comment by nahk-ivanov** [comment]
Hi,

We will try to add trigger support to the next version of the tool. Although, no ETA yet.

Thanks,
Alex.

**Comment by ijabit** [comment]
Its been a month, is there at least an ETA on this yet? I just hit the limit on our non-partitioned collection and can't import into a partitioned collection without this trigger support!

**Comment by nahk-ivanov** [comment]
Hi,

No ETA yet. I will let you know once we have our plans polished out.

Regards,
Alex.

**Comment by ijabit** [comment]
Can you at least point me to a code file where I can inject the use of a trigger myself, temporarily?

**Comment by nahk-ivanov** [comment]
Hi,

Depending on what you are trying to achieve, triggers may not be the best solution. It's definetely a generic one, which we would like to add to the tool, but if all you need is to transform the document, then I think you can inject transformation directly into the tool, as explained in [this comment](https://github.com/Azure/azure-documentdb-datamigrationtool/issues/28#issuecomment-308233868).

For the triggers, you will need to pass them as request options in the `CreateDocumentAsync` call [here](https://github.com/Azure/azure-documentdb-datamigrationtool/blob/6ab27d8eaf3ef30217e627ac8c6ab58f2fa0302f/DocumentDb/Microsoft.DataTransfer.DocumentDb/Client/DocumentDbClient.cs#L109).

Regards,
Alex.

**Comment by ijabit** [comment]
Any progress on this in the last few months?

**Comment by ijabit** [comment]
Is this going to be fixed? It's been months with no commits. Is this tool still supported?

**Comment by garfbradaz** [comment]
Trigger support would be awesome. Is this something where you would accept a PR?

@ijabit : Did you write your own Trigger support in the end?
