### ISSUE TITLE
Prevent tool from importing into a collection with TableAPI or GraphAPI

### ISSUE THREAD

**Issue by alexvy86** [Azure/azure-documentdb-datamigrationtool#30]
After 3 hours of importing (supposedly), and seeing my **Tables API** collection grow to over 1GB but not getting any results when querying for the imported entities, I finally saw the note in the [documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/import-data#AzureTableSource): "The Data Migration tool only works when importing data into Azure Cosmos DB for use with the DocumentDB API. Importing data for use with the Table API or Graph API is not supported at this time.".

I think the tool should then error out when trying to import into a collection that uses TableAPI or GraphAPI if it's not supposed to be used on those types of collections yet. It was very weird that it looked like it was importing a ton of data successfully, made my collection significantly bigger, but I couldn't see the imported entities in Data Explorer. I thought a collection set up to work with one API would just not work with the other APIs at all...? So I would have expected the tool to error out completely instead of importing data that I wasn't going to be able to query.

On a side note, would I be able to remove all those entities by using the DocumentDB API? Even though my collection was created as Table API? Or will I have to create a new collection and delete the existing one to get rid of all the "phantom" imported entities?

**Comment by AndrewHoh** [comment]
Hi @alexvy86, apologies for the confusion. We are working towards a unified schema model that will allow any API to interact with a single database. In the meantime, we are exploring different options to block different APIs from interacting with the same database. 

As for the side note, you can remove all the entities through the DocumentDB API. The fastest way to remove all the documents is to either drop the table/collection.

**Comment by alexvy86** [comment]
Thanks @AndrewHoh, I actually forked the repo and tried to see if I could implement that validation/block, but it seems that databases and collections do not currently expose the API that they were created "under", is that right? I like the plan to eventually let users use any API against a particular DB, do you have a timeline (even an approximate one) for that?

**Comment by AndrewHoh** [comment]
@alexvy86, that is correct, but this is something we are actively looking at. 

Unfortunately, we don't have a public timeline as of yet, but once we have a more confident estimate, we will let you know.
