### ISSUE TITLE
Ability to specify the allow scan header

### ISSUE THREAD

**Issue by jstawski** [Azure/azure-documentdb-datamigrationtool#32]
When importing from Cosmos Db I would like the ability to specify the Allow Scan Header so I can query even if the sql doesn't include an index property

**Comment by nkshschdv** [comment]
Did you able to solve this issue ? @jstawski

**Comment by jstawski** [comment]
Funny thing, I just ran into this issue again. I was hoping to find a solution to this problem only to find out that I was the one who reported it 4 months ago. Is this app being maintained? It is still has references to DocumentDb when it was rebranded to Cosmos Db

**Comment by Bela2711** [comment]
@jstawski https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.feedoptions.enablescaninquery?view=azure-dotnet

new FeedOptions { EnableScanInQuery = true }
This should do the work.

**Comment by jstawski** [comment]
@bella2711 how do I specify that on the data migration app?
