### ISSUE TITLE
Using TableAPIBulk - Critical error: The maximum number of operations allowed in one batch has been exceeded.

### ISSUE THREAD

**Issue by rzdebskiy** [Azure/azure-documentdb-datamigrationtool#38]
When using TableAPIBulk option for moving big tables from Azure Table Storage to Cosmos DB Table API (Premium Tables) the following exception occurs: Critical error: The maximum number of operations allowed in one batch has been exceeded.

The reason is that Cosmos DB team decided: "We have decided to keep our behavior consistent with Azure Table storage (with whom we share the same SDK) and limit batches to 100 operations."
Here is the link - please scroll to the second comment of Yaron_Goland (or just search for "100"): 
https://docs.microsoft.com/en-us/azure/cosmos-db/tutorial-develop-table-dotnet#insert-a-batch-of-entities.
There is no limit for number of operations in batch so exception occurs. I will suggest PR to fix it. Thank you in advance.

**Comment by haitsongmsft** [comment]
closing issue, PR merged.
