### ISSUE TITLE
Sql export to Geography point in Export?

### ISSUE THREAD

**Issue by retorres** [Azure/azure-documentdb-datamigrationtool#4]

**Comment by nahk-ivanov** [comment]
Can you please elaborate a little bit more what exactly is not working or what was that you were looking for?

**Comment by retorres** [comment]
how do i create a query in sql server to export to documentdb using a localization.
like
    "Localization": {
      "type": "Point",
      "coordinates": [
        -56.131702,
        -15.6048
      ]
    }

**Comment by nahk-ivanov** [comment]
As support for spatial data was just introduced recently in DocumentDB - we will definitely consider adding a native support for it into the tool for future releases. Meanwhile you can use .STAsText() + Javascript transformation. Take a look at https://github.com/Azure/azure-documentdb-datamigrationtool/blob/master/DocumentDb/Microsoft.DataTransfer.DocumentDb/BulkTransformationInsert.js for more info about data transformation during the import.

Lets keep this issue open until native support is implemented.

**Comment by nahk-ivanov** [comment]
Support for geospatial types added in b1b82765756c9b9b943a67801ad10e62ced3feb3.
