### ISSUE TITLE
DateTimeOffset values are converted to local time

### ISSUE THREAD

**Issue by tparvi** [Azure/azure-documentdb-datamigrationtool#40]
In my local cosmos db emulator I have documents where all timestamps are saved using DateTimeOffset with offset zero so they are always in UTC format like this:
2016-11-15T11:16:48.9130000+00:00

However when I export documents into a file all the timestamps are converted to local time:
2016-11-15T11:16:48.913+02:00

How do I stop this? I'm using the v1.7. Couldn't find download for v1.8 and no mention if this issue has been resolved

**Comment by Ben67366** [comment]
Seems the tools just export the datetime use default JsonSerializer settings.
You can download the source code and build Ver1.8 by yourself.
