### ISSUE TITLE
Compiling and Installing azure-documentdb-datamigrationtool

### ISSUE THREAD

**Issue by sunachuks** [Azure/azure-documentdb-datamigrationtool#45]
Hi, I need some guidance on how to go about the compilation and installation of the azure-documentdb-datamigrationtool. I have downloaded the compressed folder containing lots of files from github repository and have extracted it into a folder in my local drive, but I am currently stuck as i don't have any clue of what the next line of action should be especially since I didn't find any installation instruction in the files I have downloaded.
Could anyone with the know how kindly assist me with the steps i should take.

**Comment by Ben67366** [comment]
Do you have installed Visual Studio to compile this?
You need use some tools to compile the solution.
I've made one, you can download and use it directly.

*Compile time : 2018/3/12*
*Compile Tools: Visual Studio 2017 (Release mode)*
*From master branch.*
[Release.zip](https://github.com/Azure/azure-documentdb-datamigrationtool/files/1801606/Release.zip)

**Comment by philipvago** [comment]
Thanks BEn67366 I was able to launch this within visual studio 17
