### ISSUE TITLE
Bulk Import - PartitionKey value must be supplied for this operation

### ISSUE THREAD

**Issue by garfbradaz** [Azure/azure-documentdb-datamigrationtool#47]
# Issue

When I want to use the Migration tool to import data from a SQL Source to pre-built (i.e. manually setting up via the Portal with a PartitionKey) Collection I get the following error:

**Row 1: PartitionKey value must be supplied for this operation.**

I'm using the **DocumentDB - Bulk Import** selections, because I want to use a custom _Bulk Insert Stored Procedure_.

I though **do** include a Partition Key when setting up the target information. The funny thing is though, if I _delete_ the existing Collection and re-run the Migration Tool, it creates the Collection BUT without a Partition Key.

**FYI** I'm using the local CosmosDB Emulator.

### To get Error and no Row inserted

1. Setup a new Database and Collection in the _Local Emulator_
2. Set the **PartitionKey** up. Example I set mine up to be **/division** (**nb**: I changed the collection to Products after I took the image):

![image](https://user-images.githubusercontent.com/959766/39369307-d8e18f94-4a33-11e8-9083-dc3cb44a4124.png)

3. Within _dtui.exe_ **Source Information** I reference a query similar to [following gist](https://gist.github.com/garfbradaz/e3fb3eb7323734a1916ff9f9e7fecc59). This query is so I can use the custom stored procedure later on, to embed the **biccodes** JSON as subdocuments.
4. Within _dtui.exe_ **Target Information**, I set the following up. Note I'm including **division** in the Partition Key field.

![image](https://user-images.githubusercontent.com/959766/39369765-142ab1d8-4a35-11e8-8d40-aafc39dc5ba9.png)

5. Within _dtui.exe_ run a new Import. I get the following error:

> Row 1	Microsoft.DataTransfer.DocumentDb.Exceptions.FailedToCreateDocumentException: PartitionKey value must be supplied for this operation.    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.DataTransfer.Core.Service.DataTransferAction.<TransferDataItem>d__1.MoveNext() in F:\_Bld\16189\6357\Sources\_repo\Core\Microsoft.DataTransfer.Core\Service\DataTransferAction.cs:line 79

### Don't get an error and the Row is inserted

1. Delete the collection you created previously in the _Local Emulator_
2.  Within the _dtui.exe_ re-use the same Target Information and import
3. You will find the Collection will be created for you automatically **but without** a Partition Key assigned to the collection. As you can see NO **/division** column on the right hand side:

![image](https://user-images.githubusercontent.com/959766/39370604-42ca5ea6-4a37-11e8-9a1e-a024ed42717f.png)

![image](https://user-images.githubusercontent.com/959766/39370724-8dad68c8-4a37-11e8-99eb-9f9cafae8ce9.png)

**Comment by garfbradaz** [comment]
Any thoughts.....anyone?

**Comment by nahk-ivanov** [comment]
Hi,

As drop-down option suggests - Bulk import only support single partition collections.

Regards,
Alex.

**Comment by garfbradaz** [comment]
@nahk-ivanov : Haha, I didn't see that (or it didn't twig in my tired brain) :)

The reason I wanted to use Bulk Import is I wanted to use the Stored Procedures to handle _array_ of subdocuments within a record. Similar to an issue described here:

https://stackoverflow.com/questions/45981322/how-to-import-documents-that-have-arrays-with-the-cosmos-db-data-migration-tool[](https://stackoverflow.com/questions/45981322/how-to-import-documents-that-have-arrays-with-the-cosmos-db-data-migration-tool)

**Comment by gertaylor** [comment]
@garfbradaz did you get anywhere with this issue?

**Comment by garfbradaz** [comment]
@gertaylor : I didn't. Im going to log a separate Issue about my actual issue with array of SubDocuments from SQL-To-Cosmos. Maybe I'm missing something :)

**Comment by kevinding0218** [comment]
Wow, I'm having the exact issue with trying to migrate documents which contains the nested collections using the store procedure, @garfbradaz did you find out any solution later?
