### ISSUE TITLE
Could not load file or assembly 'MongoDB.Bson'

### ISSUE THREAD

**Issue by abelal83** [Azure/azure-documentdb-datamigrationtool#53]
When attempting to verify a mongo db connection string the tool errors

![image](https://user-images.githubusercontent.com/20558784/43151565-2014eb2a-8f64-11e8-967f-a8287c46d4de.png)

Using the latest compiled version (1.8.1) on windows 10 x64.

I've verified the file exists in the same directory as dtui.exe, anyone else have this problem?

**Comment by nahk-ivanov** [comment]
Hi,

Try downloading [v1.7](https://download.microsoft.com/download/E/1/4/E143A339-41AE-4E0E-9CC8-911C0B663478/dt-1.7.zip) and copy MongoDB.* DLLs from there.

Regards,
Alex.

**Comment by abelal83** [comment]
thanks @nahk-ivanov 

I've downloaded v1.7 and copied all MongoDB DLLs to 1.8.1 directory but the problem persists. I've tested v1.7 and that seems to work OK.

**Comment by nahk-ivanov** [comment]
Hi,

I'd just use 1.7 then, until the issue with 1.8 is resolved. I don't think there were any changes in the Mongo import in 1.8+.

Regards,
Alex.

**Comment by abelal83** [comment]
Thanks. I'll leave this issue open until 1.8 is fixed and for others in case they come across this problem.

**Comment by David-Noble-at-work** [comment]
@abelal83 ,
Thanks for reporting this issue. I've updated the tool and ask that you give it a try and let me know how it goes. You can download the tool [here](https://cosmosdbportalstorage.blob.core.windows.net/datamigrationtool/2018.02.28-1.8.1/dt-1.8.1.zip).

Best,
David Noble
