### ISSUE TITLE
Exporting Cosmos to JSON Doesn't seem to pull data

### ISSUE THREAD

**Issue by LineOfCode** [Azure/azure-documentdb-datamigrationtool#65]
When we setup the tool to pull from Cosmos and output to files, we get no errors but always get an empty JSON output as the array out - []

We have gone into the source code to look when the tool didn't seem to work.  We have used no spaces in the JSON Output nor directory (looking at other issues). 

It seems to fail @ DataTransferAction.cs the dataItem @ line 35 is not populated so it goes to 48 == null and breaks out.  As if the Cosmos Payload or query is empty or not retrieved.

**Comment by TopperKain** [comment]
To supply semi detailed reproduction steps:
1) Open the tool
2) On "Source Information", set "Import From" to document DB, then enter a valid connection string and Collection. We have tried both having a query and not having a query
3) Set "Target Information" "Export to" to JSON file and select a valid file path
4) Set no advanced config
5) On summary hit report
6) note the the JSON file is the empty array

**Comment by martinblampied** [comment]
Same. Doesn't work.

**Comment by haitsongmsft** [comment]
Please retry latest code
