### ISSUE TITLE
Package Restore Error...

### ISSUE THREAD

**Issue by lmcgs** [Azure/azure-documentdb-datamigrationtool#8]
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

**Comment by nahk-ivanov** [comment]
Can you use shorter path when you clone the repo? Currently packages are being restored to the default location, which is `packages` folder at the solution level. If this is only related to packages, then you can resolve the issue by changing the package restore folder to your preferred location through [.nuget/NuGet.config](/Azure/azure-documentdb-datamigrationtool/blob/master/.nuget/NuGet.config). You may also need to manually fix all references in csproj files to look in the new location, I'm not sure if NuGet VS extension will do that for you...
