### ISSUE TITLE
Azure TableStorage to Azure CosmosDB table Migration error

### ISSUE THREAD

**Issue by kon-iro** [Azure/azure-documentdb-datamigrationtool#89]
■Use Version
DocumentDB Data Migration Tool v1.8.2.0

■Error contents
Critical error: Direct mode is only supported with Azure CosmosDB table API service.

An error occurs Azure TableStorage to Azure CosmosDB table Migration.
I am using [dt.exe].
Is there a way to migrate using Direct Mode?

**Comment by rybkov** [comment]
Got same results. After some tries had to change couple lines of code to achieve the result.

**TableAPIBulkSinkAdapter.cs**

1. Turned off Direct Mode
`TableConnectionPolicy connectionPolicy = new TableConnectionPolicy()
            {
                UseDirectMode = false, // Turned off Direct Mode
                UseTcpProtocol = true,
            };`

2. Removed consistency and throughput as due to error - only Direct Mode supports them
`await cloudtable.CreateIfNotExistsAsync(cancellation);`

**Comment by devyash** [comment]
https://github.com/devyash/azure-documentdb-datamigrationtool/tree/azuretabletocosmosdbmigration
For anyone else who faces the same problem can directly download my branch and build it in visual studio. I did the changes mentioned above by @rybkov. Thank you

**Comment by iqsarv** [comment]
+1

**Comment by mtycholaz** [comment]
Still not fixed in 2021. And oddly enough, the gui only supports import to DocumentDb database. I'm migrating from table storage and ran into this gem. Thanks @rybkov you finally ended my 3 hours of trying to figure this out.

**Comment by codingbandit** [comment]
Hy @mtycholaz! Thank you for adding your experience to this issue. I wanted to let you know that we have started to update all of the NuGet packages/deprecated APIs in another branch. It is at the **very beginning stages** right now, but nobody has started specifically on the TableStorage to Cosmos DB project. The migration branch is dotnet6migration. We gladly accept PRs :)

**Comment by saajanjha** [comment]
@rybkov @devyash @mtycholaz  For someone new to .Net tech could you plz explain how can we build it in VS Code just for the sake of migrating data.

**Update**

To make this code change and run the application locally we followed the following steps,

1. Download Visual Code
2. Download the the project from GitHub as ZIP and unzip it.
3. Open Visual Code and select the option to open project/Solution.(Short-Ctrl+Shift+O)
4. Select the DataTransfer.sln file for import
5. Once imported, build the Microsoft.DataTransfer.ConsoleHost application by right-clicking.
6. Now add the required command line argument in the properties.
7. Start the application
