### ISSUE TITLE
Zipped blobs

### ISSUE THREAD

**Issue by bjartwolf** [Azure/azure-documentdb-datamigrationtool#9]
Had some issues trying to migrate a blob with gzipped json from Azure blob store to Document DB.

Just hacked together something for myself that unzips all files, downloaded all the files and it seems to work, but it would be better if the blob client checked for gzip and unzipped the streams before attempting to deserialize with the JsonTextReader.

**Comment by nahk-ivanov** [comment]
Resolved in 12dee7c3f05cb0b5e4bf540dba4645ba87f265ad.
