### ISSUE TITLE
Old version of migrationtool on microsoft download

### ISSUE THREAD

**Issue by jcageman** [Azure/azure-documentdb-datamigrationtool#98]
Could you please ensure https://www.microsoft.com/en-us/download/details.aspx?id=46436 is being removed or always being updated? I initially downloaded from there, but that contains a very old version which doesn't work with the latest version of COSMOS. Via this github i had to find via the issues where the latest binary release was located. Note the binary release contains 1.8.3, while according to the github releases the latest release is 1.8.1.

The link to the latest version is: https://aka.ms/csdmtool

Might be good to add that to the readme at least?

**Comment by k-miyake** [comment]
The version (currently 1.8.3) that I can get from the [download link](https://aka.ms/csdmtool) does not exist in the Release in this repository.  Is there an inconsistency between the documentation and the source code?

**Comment by ChrisCoe** [comment]
https://docs.microsoft.com/en-us/azure/cosmos-db/import-data#Install is where you can find the download link to version 1.8.3

Is there an update on this version inconsistency? Release tag on GitHub says latest is 1.8.1, git commit say latest version is 1.8.2, and the link above says version 1.8.3.

**Comment by sakash279** [comment]
1.8.3 is the latest version of the tool
